package newproj;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author tscos
 */
public class MainWindow extends javax.swing.JFrame implements Runnable {

    ArrayList<Destinations> destsReadFromFile = new ArrayList<Destinations>();

    ArrayList<Destinations> desList = new ArrayList<Destinations>();
    int[] availSeats = new int[5];

    String loggedInAccount;
    String time;
    Thread t = new Thread(this);

    /**
     * Creates new form MainWindow
     */
    public MainWindow(String loggedInAccount) {
        this.loggedInAccount = loggedInAccount;
        initComponents();
        mainLabel();
        initClock();
        loadDestinations();

    }

    public void mainLabel() {
        titleLabel.setText("Welcome to the Wellington Train Booking Service, " + loggedInAccount);
    }

    public void loadDestinations() {
        destsReadFromFile = readDestinationsFromFile("dests.txt");
        System.out.println(destsReadFromFile);
    }

    //Method populates arraylist with data from file
    public ArrayList<Destinations> readDestinationsFromFile(String fileName) {

        try {
            File file = new File(fileName);
            Scanner s = new Scanner(file);
            int i = 0;

            while (s.hasNextLine()) {

                String line = s.nextLine();
                String[] items = line.split("\\|");

                int index = Integer.parseInt(items[0]);
                String name = items[1];
                int price = Integer.parseInt(items[2]);
                int numSeats = Integer.parseInt(items[3]);

                availSeats[i] = numSeats;
                i++;

                Destinations newDest = new Destinations(index, name, price, numSeats);

                //desList.add(newDest);
                destinationList.addElement(newDest);
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Tickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        return desList;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewTicketsButton = new javax.swing.JButton();
        viewDestinationsButton = new javax.swing.JButton();
        buyTicketButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        viewTicketPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Welcome to the Wellington Train Booking Service, ");

        clock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("clock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(31, 31, 31)
                .addComponent(clock)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        viewTicketsButton.setText("View Tickets");
        viewTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTicketsButtonActionPerformed(evt);
            }
        });

        viewDestinationsButton.setText("Destinations");
        viewDestinationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDestinationsButtonActionPerformed(evt);
            }
        });

        buyTicketButton.setText("Buy Tickets");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");

        logOutButton.setText("Logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewTicketPaneLayout = new javax.swing.GroupLayout(viewTicketPane);
        viewTicketPane.setLayout(viewTicketPaneLayout);
        viewTicketPaneLayout.setHorizontalGroup(
            viewTicketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        viewTicketPaneLayout.setVerticalGroup(
            viewTicketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewDestinationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(buyTicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(viewTicketPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(viewTicketsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(636, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewTicketPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(viewDestinationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(buyTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(viewTicketsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JPanel buyTicketPanel = new JPanel();
    JPanel viewDestinations = new JPanel();
    //ticketList<String> = destsReadFromFile<String>;
    JLabel panelLabel = new JLabel();
    DefaultListModel destinationList = new DefaultListModel<>();

    JList list = new JList<>(destinationList);

    private void viewDestinationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDestinationsButtonActionPerformed
        // TODO add your handling code here:

        viewDestinations.add(list);
        //  viewDestinations.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        viewDestinations.setSize(225, 125);
        viewDestinations.setVisible(true);

        viewTicketPane.setVisible(false);
        buyTicketPanel.setVisible(false);
        viewDestinations.setVisible(true);

        viewDestinations.setLocation(220, 40);
        viewDestinations.setSize(550, 410);
        viewDestinations.setBackground(Color.green);
        panelLabel.setText("Hello");
        panelLabel.setFont(new Font("Calibri", Font.BOLD, 15));
        panelLabel.setLocation(50, 50);
        viewDestinations.add(panelLabel);

        jPanel2.add(viewDestinations);


    }//GEN-LAST:event_viewDestinationsButtonActionPerformed

    private void viewTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTicketsButtonActionPerformed
        // TODO add your handling code here:
        viewTicketPane.setVisible(true);
        buyTicketPanel.setVisible(false);
        viewDestinations.setVisible(false);
        panelLabel.setText("Purchased Tickets:");
        panelLabel.setFont(new Font("Calibri", Font.BOLD, 15));
        panelLabel.setLocation(250, 30);
        panelLabel.setSize(100, 25);
        viewTicketPane.add(panelLabel);

    }//GEN-LAST:event_viewTicketsButtonActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
        viewTicketPane.setVisible(false);

        viewDestinations.setVisible(false);

        buyTicketPanel.setLocation(220, 40);
        buyTicketPanel.setSize(550, 410);
        buyTicketPanel.setBackground(Color.red);
        buyTicketPanel.setVisible(true);

        jPanel2.add(buyTicketPanel);
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginWindow lw = new LoginWindow();
        lw.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JLabel clock;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewDestinationsButton;
    private javax.swing.JPanel viewTicketPane;
    private javax.swing.JButton viewTicketsButton;
    // End of variables declaration//GEN-END:variables

    void initClock() {
        t.start();
    }

    @Override
    public void run() {
        while (true) {

            Calendar cal = Calendar.getInstance();
            Date dat = cal.getTime();
            SimpleDateFormat sdf12 = new SimpleDateFormat("hh:mm:ss aa");
            String time12 = sdf12.format(dat);
            clock.setText(time12);

            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println("Thread killed");
                break;
            }
        }
    }
}
